local_costmap:
  # global_frame: odom
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.5


  update_frequency: 1.0
  publish_frequency: 0.5
  rolling_window: true
  width: 2
  height: 2
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


  inflation_layer:
    enabled:              true
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.04  # max. distance from an obstacle at which costs are incurred for planning paths.



