local_costmap:
   global_frame: odom #参数定义了代价地图应该运行的坐标系
   robot_base_frame: base_link #参数定义了代价地图应该为机器人的基座的坐标系。
   update_frequency: 5.0 #参数决定了代价地图更新的频率（以Hz为单位）。
   publish_frequency: 3.0 #参数决定代价地图发布可视化信息的速率（以Hz为单位）。
   #static_map: false #参数确定是否由map_server提供的地图服务来进行代价地图的初始化。
   rolling_window: true #参数设置为true意味着当机器人移动时，保持机器人在本地代价地图中心。
   width: 3.0 #代价地图宽度
   height: 3.0 #代价地图高度
   resolution: 0.1 #代价地图分辨率（米/单元格）
   transform_tolerance: 0.5
#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
   inflation_layer:
     enabled:              true #使能膨胀层
     cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
     inflation_radius:     0.03  # 机器人膨胀半径，比如设置为0.3,意味着规划的路径距离0.3米以上，这个参数理论上越大越安全
  #但是会导致无法穿过狭窄的地方

   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
  

