local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05 #increase to for higher res 0.025
  transform_tolerance: 0.5
  cost_scaling_factor: 5
  inflation_radius: 0.1

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
